/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Dineth Kariyawasam
 */
public class AddDoctor extends javax.swing.JFrame {

    /**
     * Creates new form AddDoctor
     */
    int usertype=0;
    String direction=null;
    
    public AddDoctor() {
        initComponents();
        setLocationRelativeTo(null);
        btnadd.setEnabled(false);
    }
    
    public void clearAllTextBoxes(){
        txtdocname.setText("");
        txtsetdate.setText("");
        txtaddress.setText("");
        txtnic.setText("");
        txtteleno.setText("");
        txtuserid.setText("");
        txtusername.setText("");
        txtpassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtdocname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        txtteleno = new javax.swing.JTextField();
        btncancel = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        txtdob = new datechooser.beans.DateChooserCombo();
        txtsetdate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtuserid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btngenerate = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Doctor");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Add New Doctor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Doctor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 12, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtdocname, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 24, 320, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 28, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("DOB");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 65, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Address");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtaddress.setBackground(new java.awt.Color(255, 255, 255));
        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        jScrollPane2.setViewportView(txtaddress);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("NIC");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPanel2.add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 180, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Gender");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        male.setBackground(new java.awt.Color(242, 241, 240));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        male.setText("Male");
        jPanel2.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        female.setBackground(new java.awt.Color(242, 241, 240));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        female.setText("Female");
        jPanel2.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Tele No");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        jPanel2.add(txtteleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, -1));

        btncancel.setBackground(new java.awt.Color(242, 241, 240));
        btncancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel2.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 80, 40));

        btnadd.setBackground(new java.awt.Color(242, 241, 240));
        btnadd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel2.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 80, 40));

        txtdob.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    try {
        txtdob.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    txtdob.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            txtdobOnCommit(evt);
        }
    });
    jPanel2.add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 25, -1));

    txtsetdate.setEditable(false);
    jPanel2.add(txtsetdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 130, -1));

    jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 440, 400));

    jPanel3.setBackground(new java.awt.Color(255, 255, 255));
    jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
    jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    txtuserid.setEditable(false);
    jPanel3.add(txtuserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 24, 130, -1));

    jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel13.setText("UserID");
    jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 30, -1, -1));
    jPanel3.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 60, 130, -1));

    jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel14.setText("UserName");
    jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 65, -1, -1));

    jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel15.setText("Password");
    jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 105, -1, -1));

    btngenerate.setBackground(new java.awt.Color(255, 255, 255));
    btngenerate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    btngenerate.setText("Generate");
    btngenerate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btngenerateActionPerformed(evt);
        }
    });
    jPanel3.add(btngenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));
    jPanel3.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 130, -1));

    jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 290, 190));

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/AddNewFrame1.jpg"))); // NOI18N
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        //Add New Doctor
        try {
            // TODO add your handling code here:
            Doctor newdoctor=new Doctor();
            String gender=null;
            if(male.isSelected()){
                gender="male";
            }
            else if(female.isSelected()){
                gender="female";
            }
            newdoctor.setDoctorDetails(txtdocname.getText(), txtsetdate.getText(),txtaddress.getText(), txtnic.getText(), gender, txtteleno.getText(), txtuserid.getText());
            JOptionPane.showMessageDialog(rootPane,"Successfull Added!",null,JOptionPane.INFORMATION_MESSAGE);
            txtdocname.setText("");
            txtsetdate.setText("");
            txtaddress.setText("");
            txtnic.setText("");
            txtteleno.setText("");
            txtuserid.setText("");
            txtusername.setText("");
            txtpassword.setText("");
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Error! "+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // Clear all text boxes
        txtdocname.setText("");
        txtsetdate.setText("");
        txtaddress.setText("");
        txtnic.setText("");
        txtteleno.setText("");
        txtuserid.setText("");
        txtusername.setText("");
        txtpassword.setText("");
    }//GEN-LAST:event_btncancelActionPerformed

    private void txtdobOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_txtdobOnCommit
        // Set text box date as combobox date
        txtsetdate.setText(txtdob.getText());
    }//GEN-LAST:event_txtdobOnCommit

    private void btngenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerateActionPerformed
        try {
            // Generate a username and password
            if(txtusername.getText() == null && txtpassword.getText() == null){
                JOptionPane.showMessageDialog(rootPane,"Error! Something went wrong","Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                String usertype="Doctor";
                Statement s1=Database.getStatement();
                s1.executeUpdate("INSERT INTO users(Username,Password,UserType) VALUES('"+txtusername.getText()+"','"+txtpassword.getText()+"','"+usertype+"')");
                JOptionPane.showMessageDialog(rootPane,"Successfully generated!",null,JOptionPane.INFORMATION_MESSAGE);
                Statement s2=Database.getStatement();
                ResultSet rs=s2.executeQuery("SELECT UserID,Username,Password FROM users");
                while(rs.next()){
                    txtuserid.setText(rs.getString("UserID"));
                    txtusername.setText(rs.getString("Username"));
                    txtpassword.setText(rs.getString("Password"));
                }
                btnadd.setEnabled(true);
                btngenerate.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Error! "+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btngenerateActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(() -> {
           new AddDoctor().setVisible(true);
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btngenerate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextArea txtaddress;
    private datechooser.beans.DateChooserCombo txtdob;
    private javax.swing.JTextField txtdocname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtsetdate;
    private javax.swing.JTextField txtteleno;
    private javax.swing.JTextField txtuserid;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
