/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author Dineth Kariyawasam
 */
public class AddPatient extends javax.swing.JFrame {

    /**
     * Creates new form AddPatient
     */
    int usertype=0;
    String direction=null;
    
    public AddPatient() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtpatientname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpatientaddress = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txtsetpatientdob = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        txtpatientdob = new datechooser.beans.DateChooserCombo();
        txtpatientnic = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtguardianname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtguardiannic = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtguardianteleno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtadmittedwardno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtadmittedtimeminute = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtassigneddoctorid = new javax.swing.JTextField();
        txtadmitteddate = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        txtsetadmitteddate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtadmittedtimehour = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Patient");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(242, 241, 240));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Name");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 28, -1, -1));
        jPanel3.add(txtpatientname, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 24, 290, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("DOB");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Address");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtpatientaddress.setBackground(new java.awt.Color(255, 255, 255));
        txtpatientaddress.setColumns(20);
        txtpatientaddress.setRows(5);
        jScrollPane2.setViewportView(txtpatientaddress);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("NIC");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtsetpatientdob.setEditable(false);
        jPanel3.add(txtsetpatientdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 120, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Gender");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        male.setBackground(new java.awt.Color(242, 241, 240));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        male.setText("Male");
        jPanel3.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        female.setBackground(new java.awt.Color(242, 241, 240));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        female.setText("Female");
        jPanel3.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        txtpatientdob.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    txtpatientdob.setCalendarBackground(new java.awt.Color(255, 255, 255));
    try {
        txtpatientdob.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    txtpatientdob.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            txtpatientdobOnCommit(evt);
        }
    });
    jPanel3.add(txtpatientdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 25, -1));
    jPanel3.add(txtpatientnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 180, -1));

    jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 380, 290));

    jPanel2.setBackground(new java.awt.Color(242, 241, 240));
    jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel2.setText("Name");
    jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 28, -1, -1));
    jPanel2.add(txtguardianname, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 24, 290, -1));

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel5.setText("NIC");
    jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 66, -1, -1));
    jPanel2.add(txtguardiannic, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 60, 180, -1));

    jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel12.setText("Tele No");
    jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
    jPanel2.add(txtguardianteleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 96, 180, -1));

    jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 380, 140));

    jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel14.setText("Guardian Details");
    jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

    jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel15.setText("Patient Details");
    jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

    jTabbedPane2.addTab("Patient/Guardian Details", jPanel4);

    jPanel5.setBackground(new java.awt.Color(255, 255, 255));
    jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel3.setText("Admitted Ward No");
    jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, -1, -1));
    jPanel5.add(txtadmittedwardno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 60, -1));

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel6.setText("Assigned Doctor's ID");
    jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 155, -1, -1));
    jPanel5.add(txtadmittedtimeminute, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 110, 30, -1));

    jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel13.setText("Admitted Date");
    jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 75, -1, -1));
    jPanel5.add(txtassigneddoctorid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 100, -1));

    txtadmitteddate.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
txtadmitteddate.setCalendarBackground(new java.awt.Color(255, 255, 255));
try {
    txtadmitteddate.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    txtadmitteddate.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            txtadmitteddateOnCommit(evt);
        }
    });
    jPanel5.add(txtadmitteddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 25, -1));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel1.setText("Admitted Time");
    jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 115, -1, -1));

    btncancel.setBackground(new java.awt.Color(242, 241, 240));
    btncancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    btncancel.setText("Cancel");
    btncancel.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btncancelActionPerformed(evt);
        }
    });
    jPanel5.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

    btnsubmit.setBackground(new java.awt.Color(242, 241, 240));
    btnsubmit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    btnsubmit.setText("Submit");
    btnsubmit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnsubmitActionPerformed(evt);
        }
    });
    jPanel5.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

    txtsetadmitteddate.setEditable(false);
    jPanel5.add(txtsetadmitteddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 120, -1));

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel4.setText(":");
    jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 115, 20, -1));
    jPanel5.add(txtadmittedtimehour, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 30, -1));

    jTabbedPane2.addTab("Admit Details", jPanel5);

    jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 540));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // Add new patient
        try {
            // TODO add your handling code here:
            Patient addnewpatient=new Patient();
            String gender=null;
            if(male.isSelected()){
                gender="male";
            }
            else if(female.isSelected()){
                gender="female";
            }
            String admittedtime=txtadmittedtimehour.getText()+":"+txtadmittedtimeminute.getText();
            addnewpatient.setPatientDetails(txtpatientname.getText(),txtsetpatientdob.getText(),txtpatientaddress.getText(),txtpatientnic.getText(),gender,txtguardianname.getText(),txtguardiannic.getText(),txtguardianteleno.getText(),txtadmittedwardno.getText(),txtadmitteddate.getText(),admittedtime,txtassigneddoctorid.getText());
            JOptionPane.showMessageDialog(rootPane,"Successfull Added!",null,JOptionPane.INFORMATION_MESSAGE);
            txtpatientname.setText("");
            txtpatientaddress.setText("");
            txtsetpatientdob.setText("");
            txtpatientnic.setText("");
            txtguardianname.setText("");
            txtguardiannic.setText("");
            txtguardianteleno.setText("");
            txtadmittedwardno.setText("");
            txtsetadmitteddate.setText("");
            txtadmittedtimehour.setText("");
            txtadmittedtimeminute.setText("");
            txtassigneddoctorid.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Error! "+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void txtadmitteddateOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_txtadmitteddateOnCommit
        // Set textbox text as combobox date
        txtsetadmitteddate.setText(txtadmitteddate.getText());
    }//GEN-LAST:event_txtadmitteddateOnCommit

    private void txtpatientdobOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_txtpatientdobOnCommit
        // Set textbox text as combobox date
        txtsetpatientdob.setText(txtpatientdob.getText());
    }//GEN-LAST:event_txtpatientdobOnCommit

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // Clear all textboxes
        txtpatientname.setText("");
        txtpatientaddress.setText("");
        txtsetpatientdob.setText("");
        txtpatientnic.setText("");
        txtguardianname.setText("");
        txtguardiannic.setText("");
        txtguardianteleno.setText("");
        txtadmittedwardno.setText("");
        txtsetadmitteddate.setText("");
        txtadmittedtimehour.setText("");
        txtadmittedtimeminute.setText("");
        txtassigneddoctorid.setText("");
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton male;
    private datechooser.beans.DateChooserCombo txtadmitteddate;
    private javax.swing.JTextField txtadmittedtimehour;
    private javax.swing.JTextField txtadmittedtimeminute;
    private javax.swing.JTextField txtadmittedwardno;
    private javax.swing.JTextField txtassigneddoctorid;
    private javax.swing.JTextField txtguardianname;
    private javax.swing.JTextField txtguardiannic;
    private javax.swing.JTextField txtguardianteleno;
    private javax.swing.JTextArea txtpatientaddress;
    private datechooser.beans.DateChooserCombo txtpatientdob;
    private javax.swing.JTextField txtpatientname;
    private javax.swing.JTextField txtpatientnic;
    private javax.swing.JTextField txtsetadmitteddate;
    private javax.swing.JTextField txtsetpatientdob;
    // End of variables declaration//GEN-END:variables
}
