/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Dineth Kariyawasam
 */
public class AdminMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    public AdminMainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dd = sdf.format(d);
            lblsystemdate.setText("Date : "+dd);
            
            Timer ti;
            ti = new Timer(1000, new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    Date d = new Date();
                    SimpleDateFormat sm = new SimpleDateFormat("hh:mm:ss a");
                    String dd = sm.format(d);
                    lblsystemtime.setText("Time : "+dd);
                }
            });
            ti.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblchangeuser = new javax.swing.JLabel();
        lblsystemdate = new javax.swing.JLabel();
        lblsystemtime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btndeleteusers = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnaddnewuser = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btneditusers = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btneditwards = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnaddnewward = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnmarkattendance = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Login");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblchangeuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblchangeuser.setText("You are logged in as Administrator");
        jPanel1.add(lblchangeuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        lblsystemdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblsystemdate.setText("Date : ");
        jPanel1.add(lblsystemdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, -1));

        lblsystemtime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblsystemtime.setText("Time :");
        jPanel1.add(lblsystemtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Office-Customer-Male-Light-icon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Users-Add-User-icon (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 150, 140));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/user-man-delete-icon.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 253, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Delete Users");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 345, -1, -1));

        btndeleteusers.setBackground(new java.awt.Color(255, 255, 255));
        btndeleteusers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btndeleteusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteusersActionPerformed(evt);
            }
        });
        jPanel1.add(btndeleteusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 250, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/User-Interface-Available-Updates-icon.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Add New Users");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 165, -1, -1));

        btnaddnewuser.setBackground(new java.awt.Color(255, 255, 255));
        btnaddnewuser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnaddnewuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnewuserActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddnewuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 250, 70));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Custormize Users");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 255, -1, -1));

        btneditusers.setBackground(new java.awt.Color(255, 255, 255));
        btneditusers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btneditusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditusersActionPerformed(evt);
            }
        });
        jPanel1.add(btneditusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 250, 70));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Files-Edit-File-icon.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Custormize Wards");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 255, -1, -1));

        btneditwards.setBackground(new java.awt.Color(255, 255, 255));
        btneditwards.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btneditwards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditwardsActionPerformed(evt);
            }
        });
        jPanel1.add(btneditwards, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 250, 70));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Add New Ward");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 165, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Files-Add-File-icon.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        btnaddnewward.setBackground(new java.awt.Color(255, 255, 255));
        btnaddnewward.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnaddnewward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnewwardActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddnewward, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 250, 70));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Mark Attendance");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 345, -1, -1));

        btnmarkattendance.setBackground(new java.awt.Color(255, 255, 255));
        btnmarkattendance.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnmarkattendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmarkattendanceActionPerformed(evt);
            }
        });
        jPanel1.add(btnmarkattendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 250, 70));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/textlogin.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 70));

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        LoginForm backtologin=new LoginForm();
        backtologin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnaddnewuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnewuserActionPerformed
        // TODO add your handling code here:
        AddUserFrame addnewuser=new AddUserFrame();
        addnewuser.setVisible(true);
        addnewuser.returnUserType(0);
        addnewuser.setActiveButtons(0);
        addnewuser.usertype=0;
    }//GEN-LAST:event_btnaddnewuserActionPerformed

    private void btneditusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditusersActionPerformed
        // TODO add your handling code here:
        EditUserFrame editusers=new EditUserFrame();
        editusers.setVisible(true);
        editusers.returnUserType(0);
        editusers.setActiveButtons(0);
        editusers.usertype=0;
    }//GEN-LAST:event_btneditusersActionPerformed

    private void btnaddnewwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnewwardActionPerformed
        // TODO add your handling code here:
        AddWard addnewward=new AddWard();
        addnewward.setVisible(true);
    }//GEN-LAST:event_btnaddnewwardActionPerformed

    private void btneditwardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditwardsActionPerformed
        // TODO add your handling code here:
        EditWard editward=new EditWard();
        editward.setVisible(true);
    }//GEN-LAST:event_btneditwardsActionPerformed

    private void btndeleteusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteusersActionPerformed
        // TODO add your handling code here:
        DeleteUserFrame deleteusers=new DeleteUserFrame();
        deleteusers.setVisible(true);
        deleteusers.returnUserType(0);
        deleteusers.setActiveButtons(0);
        deleteusers.usertype=0;
    }//GEN-LAST:event_btndeleteusersActionPerformed

    private void btnmarkattendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmarkattendanceActionPerformed
        // TODO add your handling code here:
        Attendance markattendance=new Attendance();
        markattendance.setVisible(true);
    }//GEN-LAST:event_btnmarkattendanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddnewuser;
    private javax.swing.JButton btnaddnewward;
    private javax.swing.JButton btndeleteusers;
    private javax.swing.JButton btneditusers;
    private javax.swing.JButton btneditwards;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmarkattendance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblchangeuser;
    private javax.swing.JLabel lblsystemdate;
    private javax.swing.JLabel lblsystemtime;
    // End of variables declaration//GEN-END:variables
}
