/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

/**
 *
 * @author Dineth Kariyawasam
 */
public class EditUserFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditUserFrame
     */
    int usertype=0;
    
    public EditUserFrame() {
        initComponents();
        setLocationRelativeTo(null);
        btneditreceptionist.setEnabled(false);
        btneditdoctor.setEnabled(false);
        btneditpatient.setEnabled(false);
        btneditlabtechnician.setEnabled(false);
    }
    
    public void returnUserType(int i){
        switch (i) {
            case 0:
                lbluser.setText("You are logged in as an Administrator");
                break;
            case 1:
                lbluser.setText("You are logged in as a Receptionist");
                break;
            case 2:
                lbluser.setText("You are logged in as a Doctor");
                break;
            case 3:
                lbluser.setText("You are logged in as a Lab Technician");
                break;
            default:
                break;
        }
    }
    
    public void setActiveButtons(int i){
        switch (i) {
            case 0:
                btneditreceptionist.setEnabled(true);
                btneditdoctor.setEnabled(true);
                btneditpatient.setEnabled(true);
                btneditlabtechnician.setEnabled(true);
                break;
            case 1:
                btneditpatient.setEnabled(true);
                break;
            case 2:
                btneditlabtechnician.setEnabled(true);
                break;
            default:
                break;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btneditreceptionist = new javax.swing.JButton();
        btneditdoctor = new javax.swing.JButton();
        btneditpatient = new javax.swing.JButton();
        btneditlabtechnician = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        lbluser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Users");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btneditreceptionist.setBackground(new java.awt.Color(242, 241, 240));
        btneditreceptionist.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        btneditreceptionist.setText("Edit Receptionists");
        btneditreceptionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditreceptionistActionPerformed(evt);
            }
        });
        jPanel1.add(btneditreceptionist, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 110, 340, 50));

        btneditdoctor.setBackground(new java.awt.Color(242, 241, 240));
        btneditdoctor.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        btneditdoctor.setText("Edit Doctors");
        btneditdoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditdoctorActionPerformed(evt);
            }
        });
        jPanel1.add(btneditdoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 170, 340, 50));

        btneditpatient.setBackground(new java.awt.Color(242, 241, 240));
        btneditpatient.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        btneditpatient.setText("Edit Patients");
        btneditpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditpatientActionPerformed(evt);
            }
        });
        jPanel1.add(btneditpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 230, 340, 50));

        btneditlabtechnician.setBackground(new java.awt.Color(242, 241, 240));
        btneditlabtechnician.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        btneditlabtechnician.setText("Edit Lab Technicians");
        btneditlabtechnician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditlabtechnicianActionPerformed(evt);
            }
        });
        jPanel1.add(btneditlabtechnician, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 290, 340, 50));

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 425, -1, -1));

        lbluser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbluser.setText("You are logged in as a");
        jPanel1.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 20));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 0));
        jLabel3.setText("Editing Users");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 1, 36)); // NOI18N
        jLabel1.setText("Editing Users");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 52, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/AddNewUserForm.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        LoginForm backtologin=new LoginForm();
        backtologin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btneditreceptionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditreceptionistActionPerformed
        // TODO add your handling code here:
        EditReceptionist editreceptionistframe=new EditReceptionist();
        editreceptionistframe.setVisible(true);
        editreceptionistframe.usertype=usertype;
        dispose();
    }//GEN-LAST:event_btneditreceptionistActionPerformed

    private void btneditdoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditdoctorActionPerformed
        // TODO add your handling code here:
        EditDoctor editdocframe=new EditDoctor();
        editdocframe.setVisible(true);
        editdocframe.usertype=usertype;
        dispose();
    }//GEN-LAST:event_btneditdoctorActionPerformed

    private void btneditpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditpatientActionPerformed
        // TODO add your handling code here:
        EditPatient editpatientframe=new EditPatient();
        editpatientframe.setVisible(true);
        editpatientframe.usertype=usertype;
        dispose();
    }//GEN-LAST:event_btneditpatientActionPerformed

    private void btneditlabtechnicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditlabtechnicianActionPerformed
        // TODO add your handling code here:
        EditLabTechnician editlabtechnicianframe=new EditLabTechnician();
        editlabtechnicianframe.setVisible(true);
        editlabtechnicianframe.usertype=usertype;
        dispose();
    }//GEN-LAST:event_btneditlabtechnicianActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditdoctor;
    private javax.swing.JButton btneditlabtechnician;
    private javax.swing.JButton btneditpatient;
    private javax.swing.JButton btneditreceptionist;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbluser;
    // End of variables declaration//GEN-END:variables
}
