/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Dineth Kariyawasam
 */
public class LabTechnicianMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form LabTechnicianMainFrame
     */
    public LabTechnicianMainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dd = sdf.format(d);
            lblsystemdate.setText("Date : "+dd);
            
            Timer ti;
            ti = new Timer(1000, new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    Date d = new Date();
                    SimpleDateFormat sm = new SimpleDateFormat("hh:mm:ss a");
                    String dd = sm.format(d);
                    lblsystemtime.setText("Time : "+dd);
                }
            });
            ti.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblchangeuser = new javax.swing.JLabel();
        lblsystemdate = new javax.swing.JLabel();
        lblsystemtime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnviewrequests = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btneditrequests = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnaddnewreports = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lab Technician Login");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblchangeuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblchangeuser.setText("You are logged in as a Lab Technician");
        jPanel1.add(lblchangeuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        lblsystemdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblsystemdate.setText("Date : ");
        jPanel1.add(lblsystemdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, -1));

        lblsystemtime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblsystemtime.setText("Time :");
        jPanel1.add(lblsystemtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Office-Customer-Male-Light-icon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Business-Make-Decision-icon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 50, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/User-Interface-Available-Updates-icon.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("View Requests");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 165, -1, -1));

        btnviewrequests.setBackground(new java.awt.Color(255, 255, 255));
        btnviewrequests.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnviewrequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewrequestsActionPerformed(evt);
            }
        });
        jPanel1.add(btnviewrequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 250, 70));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Edit Requests");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 255, -1, -1));

        btneditrequests.setBackground(new java.awt.Color(255, 255, 255));
        btneditrequests.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btneditrequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditrequestsActionPerformed(evt);
            }
        });
        jPanel1.add(btneditrequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 250, 70));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Add New Reports");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 165, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Files-Add-File-icon.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        btnaddnewreports.setBackground(new java.awt.Color(255, 255, 255));
        btnaddnewreports.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnaddnewreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnewreportsActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddnewreports, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 250, 70));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/textlogin.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 70));

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnviewrequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewrequestsActionPerformed
        // TODO add your handling code here:
        ViewRequests viewrequests=new ViewRequests();
        viewrequests.setVisible(true);
    }//GEN-LAST:event_btnviewrequestsActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        LoginForm backtologin=new LoginForm();
        backtologin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnaddnewreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnewreportsActionPerformed
        // TODO add your handling code here:
        LabTests addnewtest=new LabTests();
        addnewtest.setVisible(true);
    }//GEN-LAST:event_btnaddnewreportsActionPerformed

    private void btneditrequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditrequestsActionPerformed
        // TODO add your handling code here:
        EditRequests editrequests=new EditRequests();
        editrequests.setVisible(true);
    }//GEN-LAST:event_btneditrequestsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabTechnicianMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabTechnicianMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabTechnicianMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabTechnicianMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabTechnicianMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddnewreports;
    private javax.swing.JButton btneditrequests;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnviewrequests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblchangeuser;
    private javax.swing.JLabel lblsystemdate;
    private javax.swing.JLabel lblsystemtime;
    // End of variables declaration//GEN-END:variables
}
